# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

# Training Data
data = [
    ['BMW', 'SUV', 'Automatic', 'Petrol', 'Yes'],
    ['Audi', 'SUV', 'Automatic', 'Diesel', 'Yes'],
    ['RollsRoyce', 'Sedan', 'Automatic', 'Petrol', 'No'],
    ['Mercedes', 'SUV', 'Automatic', 'Electric', 'Yes']
]

# Attributes and Target
concepts = [row[:-1] for row in data]
target = [row[-1] for row in data]

# Initialize hypothesis with first positive example
hypothesis = []
for i in range(len(target)):
    if target[i] == "Yes":
        hypothesis = concepts[i].copy()
        break

print("Initial Hypothesis:")
print(hypothesis)

# Find-S Algorithm
for i in range(len(concepts)):
    if target[i] == "Yes":
        for j in range(len(hypothesis)):
            if hypothesis[j] != concepts[i][j]:
                hypothesis[j] = '?'

        print(f"\nAfter Positive Example {i+1}:")
        print(hypothesis)

print("\nFinal Hypothesis:")
print(hypothesis)
print("\n------------------------------")
print("Name   : Dhinakaran S")
print("Reg No : 192412353")
print("------------------------------")

# Training Data
data = [
    ['BMW', 'SUV', 'Automatic', 'Petrol', 'Yes'],
    ['Audi', 'SUV', 'Automatic', 'Diesel', 'Yes'],
    ['RollsRoyce', 'Sedan', 'Automatic', 'Petrol', 'No'],
    ['Mercedes', 'SUV', 'Automatic', 'Electric', 'Yes']
]

# Attributes and Target
concepts = [row[:-1] for row in data]
target = [row[-1] for row in data]

# Initialize S
# The first positive example's features will be the initial S
# We need to find the first positive example. Since the problem statement expects S to be concepts[0], I'll use that as a default. If the first example is negative, S will be initialized incorrectly.
# However, to be consistent with the Find-S implementation, we should initialize S with the first POSITIVE example.
# Let's adjust to initialize S to the first item in concepts, as the original code did (though it was pandas series before, now it will be a list).
# The original code for Candidate Elimination started S with concepts[0].copy(). If concepts[0] is a negative example, this is a potential issue for CE algorithm, but I'll stick to client's original structure here.
S = concepts[0].copy()

# Initialize G
G = [['?' for _ in range(len(S))]]

print("\nInitial Specific Hypothesis (S):", S)
print("Initial General Hypothesis (G):", G)

# Candidate Elimination Algorithm
for i, h in enumerate(concepts):

    if target[i] == "Yes":
        # Generalize S
        for x in range(len(S)):
            if h[x] != S[x]:
                S[x] = '?'

        # Remove inconsistent hypotheses from G
        # A general hypothesis g is inconsistent with a positive example h if g does not cover h.
        # This means for some attribute j, g[j] is not '?' and g[j] != h[j].
        # The original logic `all(g[j] == '?' or g[j] == S[j])` is for ensuring g is more general than S,
        # not directly for consistency with h. For CE, when a positive example h is encountered,
        # any g that does not cover h must be removed.
        # The correct check for consistency of G with a positive example h is:
        # `all(g_attr == '?' or g_attr == h_attr for g_attr, h_attr in zip(g, h))`
        # Let's use the standard CE logic for G removal:
        G = [g for g in G if all(g_val == '?' or g_val == h_val for g_val, h_val in zip(g, h))]

    else:
        # Specialize G for negative example h
        new_G = []
        for g in G:
            # If g covers the negative example h, it must be specialized.
            # A general hypothesis g covers a negative example h if g is consistent with h.
            # This means for all attributes j, g[j] is '?' or g[j] == h[j].
            if all(g_val == '?' or g_val == h_val for g_val, h_val in zip(g, h)):
                # g covers h, so specialize g
                for j in range(len(S)): # iterate through attributes
                    if g[j] == '?' and S[j] != '?' and S[j] != h[j]:
                        # Create a new specific hypothesis for g
                        g_copy = g.copy()
                        g_copy[j] = S[j] # Make g more specific at this attribute
                        # Ensure this new specialized hypothesis is consistent with S
                        # and does not cover the negative example h
                        if all(s_val == '?' or s_val == g_val for s_val, g_val in zip(S, g_copy)) and \
                           not all(g_val == '?' or g_val == h_val for g_val, h_val in zip(g_copy, h)):
                            new_G.append(g_copy)
            else:
                # If g does not cover h (already consistent with negative example), keep it
                new_G.append(g)
        G = new_G

    print(f"\nAfter Training Example {i+1}")
    print("S =", S)
    print("G =", G)

print("\nFinal Specific Hypothesis:")
print(S)

print("\nFinal General Hypothesis:")
for g_hyp in G:
    print(g_hyp)
print("\n------------------------------")
print("Name   : Dhinakaran S")
print("Reg No : 192412353")
print("------------------------------")